export const projects = [
    {
        title: "MeditaZone App",
        alt: "Cloud Engineer",
        description: "A mobile application developed specifically for the Capstone Project, using Machine Learning technology to predict mental disorders.",
        image: "/meditazone.png",
        url: "https://github.com/nugrohoarr/meditazone",
        techs: ["Express.js", "Flask", "GCP"],
    },
    {
        title: "SpinCycle",
        alt: "Backend Developer",
        description: "The SpinCycle Machine Learning API is a RESTful service designed to offer personalized recommendations for nearby laundry services. By leveraging user location data and specific service requirements, the API identifies the most suitable laundry options, including express services, delivery options, and specialized care for delicate fabrics. Whether you're in a hurry or need particular attention for your garments, SpinCycle ensures you find the perfect laundry service quickly and efficiently.",
        image: "apalah.svg",
        url: "https://documenter.getpostman.com/view/26309282/2sA3XS9Kzx#8c3f441a-97ef-48e5-96a7-7d1b3957d786",
        techs: ["Nest.js", "Flask", "GCP"],
    },
    {
        title: "Penjurian Jemparingan",
        alt: "Backend Developer",
        description: "A web application for the judging system of the jemparingan competition conducted by Pakualaman.",
        image: "pakualaman.png",
        url: "https://jemparinganpakualaman.id/",
        techs: ["Fullstack", "Nginx", "CI/CD"],
    },
    {
        title: "SiLangka App",
        alt: "Backend Developer",
        description: "Mobile application designed to facilitate the reporting and monitoring of protected animals found around Senakin. The app actively supports protected species conservation.",
        image: "silang.png",
        url: "/",
        techs: ["Nest.js", "PostgreSQL", "Docker"],
    },
    {
        title: "UKM-IK Website",
        alt: "Backend Developer",
        description: "A website that provides information about the organization and the recruitment process of new UKM Informatika dan Komputer members.",
        image: "ukmik-oms.png",
        url: "https://ukmik.utdi.ac.id/",
        techs: ["Nest.js", "PostgreSQL", "Docker"],
    },
    
    {
        title: "EcoSort Website",
        alt: "Frontend Developer",
        description: "A website designed specifically for the Software Development Competition that aims to address the issue of waste management.",
        image: "EcoSort.png",
        url: "https://fe-eco-storter.vercel.app/",
        techs: ["React.js", "Tailwind", "Docker"],
    },
    {
        title: "Portofolio Website",
        alt: "Frontend Developer",
        description: "A website designed specifically for the personal portfolio build with Next.js, Tailwind, and shadcn/ui .",
        image: "v2.png",
        url: "https://nugrohoar.info/",
        techs: ["Next.js", "shadcn/Ui"],
    },
];