export const projects = [
    {
        title: "MeditaZone App",
        alt: "Cloud Engineer",
        description: "A mobile application developed specifically for the Capstone Project, using Machine Learning technology to predict mental disorders.",
        image: "/meditazone.png",
        url: "https://github.com/nugrohoarr/meditazone",
        techs: ["Express.js", "Flask", "GCP"],
    },
    {
        title: "SiLangka App",
        alt: "Backend Developer",
        description: "Mobile application designed to facilitate the reporting and monitoring of protected animals found around Senakin. The app actively supports protected species conservation.",
        image: "SiLangka.png",
        url: "https://api-arutmin.up.railway.app/v1/api/",
        techs: ["Nest.js", "PostgreSQL", "Docker"],
    },
    {
        title: "UKM-IK Website",
        alt: "Backend Developer",
        description: "A website that provides information about the organization and the recruitment process of new UKM Informatika dan Komputer members.",
        image: "ukmik-oms.png",
        url: "https://ukmik.utdi.ac.id/",
        techs: ["Nest.js", "PostgreSQL", "Docker"],
    },
    {
        title: "EcoSort Website",
        alt: "Frontend Developer",
        description: "A website designed specifically for the Software Development Competition that aims to address the issue of waste management.",
        image: "EcoSort.png",
        url: "https://fe-eco-storter.vercel.app/",
        techs: ["React.js", "Tailwind", "Docker"],
    },
    {
        title: "Portofolio Website",
        alt: "Frontend Developer",
        description: "A website designed specifically for the personal portfolio build with Next.js, Tailwind, and shadcn/ui .",
        image: "porto.png",
        url: "https://nugrohoar.info/",
        techs: ["Next.js", "shadcn/Ui"],
    },
];